
<?php

/*
	besttraveltime 
	(if may-august then -> 23) later asked str_contains
	a number is given if 2 or more months are included
	sources: https://wetter-atlas.de/
			 https://wohin-und-wann.de/
			 https://diebestereisezeit.de/
			 https://www.urlaubsguru.de/
	1=>DEZ-FEB
	2=>MAR-MAY
	3=>JUN-AUG
	4=>SEP-NOV 
	*/
	$countryarray = array(
		0 => array (
			'name'=>'#abudhabi',
			'count'=>0,
			'besttraveltime'=> '1',
			'group'=>'',
		),
		1 => array (
			'name'=>'#admiralty', 
			'count'=>0,
			'besttraveltime'=>'3',
			'group'=>'#papuanewguinea',
		),
		2 => array (
			'name'=>'#afghanistan',
			'count'=>0,
			'besttraveltime'=> '24',
			'group'=>'',
		),
		3 => array (
			'name'=>'#aitutaki', 
			'count'=>0,
			'besttraveltime'=> '234',
			'group'=>'#cookislands',
		),
		4 => array (
			'name'=>'#ajman', 
			'count'=>0,
			'besttraveltime'=> '12',
			'group'=>'#emirates',
		),
		5 => array (
			'name'=>'#åland', 
			'count'=>0,
			'besttraveltime'=> '3',
			'group'=>'#finnland',
		),
		6 => array (
			'name'=>'#albania',
			'count'=>0,
			'besttraveltime'=> '234',
			'group'=>'',
		),
		7 => array (
			'name'=>'#alberta', 
			'count'=>0,
			'besttraveltime'=> '3',
			'group'=>'#canada',
		),
		8 => array (
			'name'=>'#alderney', 
			'count'=>0,
			'besttraveltime'=> '34',
			'group'=>'#greatbritain', 
		),
		9 => array (
			'name'=>'#algeria',
			'count'=>0,
			'besttraveltime'=> '234',
			'group'=>'',
		),
		10 => array (
			'name'=>'#alhucemas', //spain
			'count'=>0,
			'besttraveltime'=> '34',
			'group'=>'#spain',
		),
		11 => array (
			'name'=>'#alofi', //caledonia
			'count'=>0,
			'besttraveltime'=> '34',
			'group'=>'#newcaledonia',
		),
		12 => array (
			'name'=>'#samoa',
			'count'=>0,
			'besttraveltime'=> '34',
			'group'=>'',
		),
		13 => array (
			'name'=>'#andaman',
			'count'=>0,
			'besttraveltime'=> '12',
			'group'=>'',
		),
		14 => array (
			'name'=>'#andorra',
			'count'=>0,
			'besttraveltime'=> '234',
			'group'=>'',
		),
		15 => array (
			'name'=>'#angola',
			'count'=>0,
			'besttraveltime'=> '4',
			'group'=>'',
		),
		16 => array (
			'name'=>'#anguilla',
			'count'=>0,
			'besttraveltime'=> '3',
			'group'=>'#caribbeanislands',
		),
		17 => array (
			'name'=>'#anjouan', 
			'count'=>0,
			'besttraveltime'=> '34',
			'group'=>'#comoros',
		),
		18 => array (
			'name'=>'#annobon', 
			'count'=>0,
			'besttraveltime'=> '1234',
			'group'=>'#equatorialguinea',
		),
		19 => array (
			'name'=>'#antigua',
			'count'=>0,
			'besttraveltime'=> '12',
			'group'=>'#caribbeanislands',
		),
		20 => array (
			'name'=>'#barbuda',
			'count'=>0,
			'besttraveltime'=> '12',
			'group'=>'#caribbeanislands',
		),
		21 => array (
			'name'=>'#argentina',
			'count'=>0,
			'besttraveltime'=> '24',
			'group'=>'',
		),
		22 => array (
			'name'=>'#armenia',
			'count'=>0,
			'besttraveltime'=> '24',
			'group'=>'',
		),
		23 => array (
			'name'=>'#aruba',
			'count'=>0,
			'besttraveltime'=> '23',
			'group'=>'',
		),
		24 => array (
			'name'=>'#ascension',
			'count'=>0,
			'besttraveltime'=> '3',
			'group'=>'',
		),
		25 => array (
			'name'=>'#astypalaia', 
			'count'=>0,
			'besttraveltime'=> '23',
			'group'=>'#greece',
		),
		26 => array (
			'name'=>'#atafu',
			'count'=>0,
			'besttraveltime'=> '34',
			'group'=>'#samoa',
		),
		27 => array (
			'name'=>'#atiu',
			'count'=>0,
			'besttraveltime'=> '234',
			'group'=>'#cookislands',
		),
		28 => array (
			'name'=>'#australia',
			'count'=>0,
			'besttraveltime'=>'124',
			'group'=>'',
		),
		29 => array (
			'name'=>'#austria',
			'count'=>0,
			'besttraveltime'=> '134',
			'group'=>'',
		),
		30 => array (
			'name'=>'#avarua',
			'count'=>0,
			'besttraveltime'=> '3',
			'group'=>'#cookislands',
		),
		31 => array (
			'name'=>'#azerbaijan',
			'count'=>0,
			'besttraveltime'=> '24',
			'group'=>'',
		),
		32 => array (
			'name'=>'#azores',
			'count'=>0,
			'besttraveltime'=> '3',
			'group'=>'',
		),
		33 => array (
			'name'=>'#belgium',
			'count'=>0,
			'besttraveltime'=> '3',
			'group'=>'',
		),
		34 => array (
			'name'=>'#belarus',
			'count'=>0,
			'besttraveltime'=>'3',
			'group'=>'',
		),
		35 => array (
			'name'=>'#bahamas',
			'count'=>0,
			'besttraveltime'=> '12',
			'group'=>'',
		),
		36 => array (
			'name'=>'#bahrain',
			'count'=>0,
			'besttraveltime'=> '1',
			'group'=>'',
		),
		37 => array (
			'name'=>'#baleares',
			'count'=>0,
			'besttraveltime'=> '3',
			'group'=>'',
		),
		38 => array (
			'name'=>'#balochistan',
			'count'=>0,
			'besttraveltime'=> '4',
			'group'=>'#pakistan',
		),
		39 => array (
			'name'=>'#bangladesh',
			'count'=>0,
			'besttraveltime'=> '1',
			'group'=>'',
		),
		40 => array (
			'name'=>'#barbados',
			'count'=>0,
			'besttraveltime'=> '2',
			'group'=>'#caribbeanislands',
		),
		41 => array (
			'name'=>'#caribbeanislands',
			'count'=>0,
			'besttraveltime'=>'12',
			'group'=>'',
		),
		42 => array (
			'name'=>'#barthelemy',
			'count'=>0,
			'besttraveltime'=>'23',
			'group'=>'#caribbeanislands',
		),
		43 => array (
			'name'=>'#belize',
			'count'=>0,
			'besttraveltime'=>'12',
			'group'=>'#guatemala',
		),
		44 => array (
			'name'=>'#benin',
			'count'=>0,
			'besttraveltime'=>'13',
			'group'=>'',
		),
		45 => array (
			'name'=>'#bermuda',
			'count'=>0,
			'besttraveltime'=>'1234',
			'group'=>'',
		),
		46 => array (
			'name'=>'#bhutan',
			'count'=>0,
			'besttraveltime'=>'24',
			'group'=>'',
		),
		47 => array (
			'name'=>'#bolivia',
			'count'=>0,
			'besttraveltime'=>'34',
			'group'=>'',
		),
		48 => array (
			'name'=>'#bonaire',
			'count'=>0,
			'besttraveltime'=>'12',
			'group'=>'#curacao',
		),
		49 => array (
			'name'=>'#borabora',
			'count'=>0,
			'besttraveltime'=>'3',
			'group'=>'',
		),
		50 => array (
			'name'=>'#borneo',
			'count'=>0,
			'besttraveltime'=>'23',
			'group'=>'#indonesia',
		),
		51 => array (
			'name'=>'#bosnia',
			'count'=>0,
			'besttraveltime'=>'3',
			'group'=>'',
		),
		52 => array (
			'name'=>'#botswana',
			'count'=>0,
			'besttraveltime'=>'34',
			'group'=>'',
		),
		53 => array (
			'name'=>'#bougainville',
			'count'=>0,
			'besttraveltime'=>'3',
			'group'=>'#papuanewguinea',
		),
		54 => array (
			'name'=>'#bourbon',
			'count'=>0,
			'besttraveltime'=>'34',
			'group'=>'#mauritius',
		),
		55 => array (
			'name'=>'#brazil',
			'count'=>0,
			'besttraveltime'=>'234',
			'group'=>'',
		),
		56 => array (
			'name'=>'#britishcolumbia',
			'count'=>0,
			'besttraveltime'=>'34',
			'group'=>'#canada',
		),
		57 => array (
			'name'=>'#virginislands',
			'count'=>0,
			'group'=>'#caribbeanislands',
			'besttraveltime'=>'12',
		),
		58 => array (
			'name'=>'#bruneidarussalam',
			'count'=>0,
			'besttraveltime'=>'23',
			'group'=>'#indonesia',
		),
		59 => array (
			'name'=>'#buka',
			'count'=>0,
			'besttraveltime'=>'234',
			'group'=>'#papuanewguinea',
		),
		60 => array (
			'name'=>'#bulgaria',
			'count'=>0,
			'besttraveltime'=>'34',
			'group'=>'',
		),
		61 => array (
			'name'=>'#burkinafaso',
			'count'=>0,
			'besttraveltime'=>'1',
			'group'=>'',
		),
		62 => array (
			'name'=>'#burma',
			'count'=>0,
			'besttraveltime'=>'14',
			'group'=>'',
		),
		63 => array (
			'name'=>'#burundi',
			'count'=>0,
			'besttraveltime'=>'34',
			'group'=>'',
		),
		64 => array (
			'name'=>'#caicos',
			'count'=>0,
			'besttraveltime'=>'12',
			'group'=>'#turksandcaicosislands',
		),
		65 => array (
			'name'=>'#zanzibar',
			'count'=>0,
			'besttraveltime'=>'134',
			'group'=>'',
		),
		66 => array (
			'name'=>'#cameroon',
			'count'=>0,
			'besttraveltime'=>'14',
			'group'=>'',
		),
		67 => array (
			'name'=>'#canada',
			'count'=>0,
			'besttraveltime'=>'34',
			'group'=>'',
		),
		68 => array (
			'name'=>'#canaryislands',
			'count'=>0,
			'besttraveltime'=>'234',
			'group'=>'',
		),
		69 => array (
			'name'=>'#cantonisland',
			'count'=>0,
			'besttraveltime'=>'34',
			'group'=>'#kiribati',
		),
		70 => array (
			'name'=>'#capeverde',
			'count'=>0,
			'besttraveltime'=>'12',
			'group'=>'',
		),
		71 => array (
			'name'=>'#caymanislands',
			'count'=>0,
			'besttraveltime'=>'12',
			'group'=>'',
		),
		72 => array (
			'name'=>'#centralafricanrepublic',
			'count'=>0,
			'besttraveltime'=>'1',
			'group'=>'',
		),
		73 => array (
			'name'=>'#ceuta',
			'count'=>0,
			'besttraveltime'=>'3',
			'group'=>'#spain',
		),
		74 => array (
			'name'=>'#ceylon',
			'count'=>0,
			'besttraveltime'=>'1234',
			'group'=>'#srilanka',
		),
		75 => array (
			'name'=>'#chad',
			'count'=>0,
			'besttraveltime'=>'1',
			'group'=>'',
		),
		76 => array (
			'name'=>'#chalki',
			'count'=>0,
			'besttraveltime'=>'3',
			'group'=>'#greece',
		),
		77 => array (
			'name'=>'#channelislands',
			'count'=>0,
			'besttraveltime'=>'3',
			'group'=>'#greatbritain',
		),
		78 => array (
			'name'=>'#chile',
			'count'=>0,
			'besttraveltime'=>'124',
			'group'=>'',
		),
		79 => array (
			'name'=>'#china',
			'count'=>0,
			'besttraveltime'=>'4',
			'group'=>'',
		),
		80 => array (
			'name'=>'#christmasisland',
			'count'=>0,
			'besttraveltime'=>'34',
			'group'=>'#kiribati',
		),
		81 => array (
			'name'=>'#cocosisland',
			'count'=>0,
			'besttraveltime'=>'3',
			'group'=>'#australia',
		),
		82 => array (
			'name'=>'#columbia',
			'count'=>0,
			'besttraveltime'=>'13',
			'group'=>'',
		),
		83 => array (
			'name'=>'#comoros',
			'count'=>0,
			'besttraveltime'=>'234',
			'group'=>'',
		),
		84 => array (
			'name'=>'#congo',
			'count'=>0,
			'besttraveltime'=>'3',
			'group'=>'',
		),
		85 => array (
			'name'=>'#cookislands',
			'count'=>0,
			'besttraveltime'=>'234',
			'group'=>'',
		),
		86 => array (
			'name'=>'#corisco',
			'count'=>0,
			'besttraveltime'=>'1',
			'group'=>'#equatorialguinea',
		),
		87 => array (
			'name'=>'#corsica',
			'count'=>0,
			'besttraveltime'=>'3',
			'group'=>'#france',
		),
		88 => array (
			'name'=>'#costarica',
			'count'=>0,
			'besttraveltime'=>'12',
			'group'=>'',
		),
		89 => array (
			'name'=>'#cotedivoire',
			'count'=>0,
			'besttraveltime'=>'1',
			'group'=>'#ivorycoast',
		),
		90 => array (
			'name'=>'#crete',
			'count'=>0,
			'besttraveltime'=>'234',
			'group'=>'#greece',
		),
		91 => array (
			'name'=>'#croatia',
			'count'=>0,
			'besttraveltime'=>'34',
			'group'=>'',
		),
		92 => array (
			'name'=>'#cuba',
			'count'=>0,
			'besttraveltime'=>'12',
			'group'=>'',
		),
		93 => array (
			'name'=>'#cuminoisland',
			'count'=>0,
			'besttraveltime'=>'34',
			'group'=>'#malta',
		),
		94 => array (
			'name'=>'#curacao',
			'count'=>0,
			'besttraveltime'=>'1234',
			'group'=>'',
		),
		95 => array (
			'name'=>'#cyprus',
			'count'=>0,
			'besttraveltime'=>'24',
			'group'=>'',
		),
		96 => array (
			'name'=>'#czechrepublic',
			'count'=>0,
			'besttraveltime'=>'3',
			'group'=>'',
		),
		97 => array (
			'name'=>'#dangerisland',
			'count'=>0,
			'besttraveltime'=>'1234',
			'group'=>'#newzealand',
		),
		98 => array (
			'name'=>'#denmark',
			'count'=>0,
			'besttraveltime'=>'3',
			'group'=>'',
		),
		99 => array (
			'name'=>'#diu',
			'count'=>0,
			'besttraveltime'=>'14',
			'group'=>'#india ',
		),
		100 => array (
			'name'=>'#djibouti',
			'count'=>0,
			'besttraveltime'=>'1',
			'group'=>'',
		),
		101 => array (
			'name'=>'#dodecanese',
			'count'=>0,
			'besttraveltime'=>'3',
			'group'=>'#greece',
		),
		102 =>array (
			'name'=>'#doha',
			'count'=>0,
			'besttraveltime'=>'24',
			'group'=>'#qatar',
		),
		103 => array (
			'name'=>'#dominica',
			'count'=>0,
			'besttraveltime'=>'12',
			'group'=>'#caribbeanislands',
		),
		104 => array (
			'name'=>'#domenican',
			'count'=>0,
			'besttraveltime'=>'34',
			'group'=>'',
		),
		105 => array (
			'name'=>'#dubai',
			'count'=>0,
			'besttraveltime'=>'12',
			'group'=>'#emirates',
		),
		106 => array (
			'name'=>'#easttimor',
			'count'=>0,
			'besttraveltime'=>'34',
			'group'=>'#indonesia',
		),
		107 => array (
			'name'=>'#equador',
			'count'=>0,
			'besttraveltime'=>'13',
			'group'=>'',
		),
		108 => array (
			'name'=>'#egypt',
			'count'=>0,
			'besttraveltime'=>'124',
			'group'=>'',
		),
		109 => array (
			'name'=>'#mexico',
			'count'=>0,
			'besttraveltime'=>'12',
			'group'=>'#ireland',
		),
		110 => array (
			'name'=>'#elsalvador',
			'count'=>0,
			'besttraveltime'=>'12',
			'group'=>'',
		),
		111 => array (
			'name'=>'#uk ',
			'count'=>0,
			'besttraveltime'=>'3',
			'group'=>'',
		),
		112 => array (
			'name'=>'#equatorialguinea',
			'count'=>0,
			'besttraveltime'=>'1',
			'group'=>'',
		),
		113 => array (
			'name'=>'#eritrea',
			'count'=>0,
			'besttraveltime'=>'14',
			'group'=>'',
		),
		114 => array (
			'name'=>'#estonia',
			'count'=>0,
			'besttraveltime'=>'3',
			'group'=>'',
		),
		115 => array (
			'name'=>'#ethiopia',
			'count'=>0,
			'besttraveltime'=>'124',
			'group'=>'',
		),
		116 => array (
			'name'=>'#fakaofo',
			'count'=>0,
			'besttraveltime'=>'234',
			'group'=>'#samoa',
		),
		117 => array (
			'name'=>'#falklandislands',
			'count'=>0,
			'besttraveltime'=>'1',
			'group'=>'',
		),
		118 => array (
			'name'=>'#fanningisland',
			'count'=>0,
			'besttraveltime'=>'34',
			'group'=>'#kirbati',
		),
		119 => array (
			'name'=>'#faroeislands',
			'count'=>0,
			'besttraveltime'=>'23',
			'group'=>'',
		),
		120 => array (
			'name'=>'#fiji',
			'count'=>0,
			'besttraveltime'=>'24',
			'group'=>'',
		),
		121 => array (
			'name'=>'#finland',
			'count'=>0,
			'besttraveltime'=>'1',
			'group'=>'',
		),
		122 => array (
			'name'=>'#france',
			'count'=>0,
			'besttraveltime'=>'24',
			'group'=>'',
		),
		123 => array (
			'name'=>'#frenchguiana',
			'count'=>0,
			'besttraveltime'=>'',
			'group'=>'',
		),
		124 => array (
			'name'=>'#frenchpolynesia',
			'count'=>0,
			'besttraveltime'=>'34',
			'group'=>'',
		),
		125 => array (
			'name'=>'#guadeloupe',
			'count'=>0,
			'besttraveltime'=>'12',
			'group'=>'#caribbeanislands',
		),
		126 => array (
			'name'=>'#martinique',
			'count'=>0,
			'besttraveltime'=>'12',
			'group'=>'#caribbeanislands',
		),
		127 => array (
			'name'=>'#friendlyislands',
			'count'=>0,
			'besttraveltime'=>'34',
			'group'=>'#tonga',
		),
		128 => array (
			'name'=>'#fujairah',
			'count'=>0,
			'besttraveltime'=>'12',
			'group'=>'#emirates',
		),
		129 => array (
			'name'=>'#futuna',
			'count'=>0,
			'besttraveltime'=>'234',
			'group'=>'#futuna',
		),
		130 => array (
			'name'=>'#wallisisland',
			'count'=>0,
			'besttraveltime'=>'234',
			'group'=>'#futuna',
		),
		131 => array (
			'name'=>'#gabon',
			'count'=>0,
			'besttraveltime'=>'13',
			'group'=>'',
		),
		132 => array (
			'name'=>'#gambia',
			'count'=>0,
			'besttraveltime'=>'12',
			'group'=>'',
		),
		133 => array (
			'name'=>'#gambier',
			'count'=>0,
			'besttraveltime'=>'234',
			'group'=>'#frenchpolynesia',
		),
		134 => array (
			'name'=>'#georgia🇬🇪',
			'count'=>0,
			'besttraveltime'=>'24',
			'group'=>'',
		),
		135 => array (
			'name'=>'#germany',
			'count'=>0,
			'besttraveltime'=>'3',
			'group'=>'',
		),
		136 => array (
			'name'=>'#ghana',
			'count'=>0,
			'besttraveltime'=>'1',
			'group'=>'',
		),
		137 => array (
			'name'=>'#gibraltar',
			'count'=>0,
			'besttraveltime'=>'234',
			'group'=>'',
		),
		138 => array (
			'name'=>'#goa',
			'count'=>0,
			'besttraveltime'=>'12',
			'group'=>'#india ',
		),
		139 => array (
			'name'=>'#gozoisland',
			'count'=>0,
			'besttraveltime'=>'34',
			'group'=>'#malta',
		),
		140 => array (
			'name'=>'#comoros',
			'count'=>0,
			'besttraveltime'=>'34',
			'group'=>'',
		),
		141 => array (
			'name'=>'#greece',
			'count'=>0,
			'besttraveltime'=>'234',
			'group'=>'',
		),
		142 => array (
			'name'=>'#greenland',
			'count'=>0,
			'besttraveltime'=>'23',
			'group'=>'',
		),
		143 => array (
			'name'=>'#grenada',
			'count'=>0,
			'besttraveltime'=>'12',
			'group'=>'',
		),
		144 => array (
			'name'=>'#grenadines',
			'count'=>0,
			'besttraveltime'=>'12',
			'group'=>'#caribbeanislands',
		),
		145 => array (
			'name'=>'#lesotho',
			'count'=>0,
			'besttraveltime'=>'24',
			'group'=>'',
		),
		146 => array (
			'name'=>'#guatemala',
			'count'=>0,
			'besttraveltime'=>'124',
			'group'=>'',
		),
		147 => array (
			'name'=>'#guernsey',
			'count'=>0,
			'besttraveltime'=>'34',
			'group'=>'#greatbritain',
		),
		148 => array (
			'name'=>'#guinea',
			'count'=>0,
			'besttraveltime'=>'12',
			'group'=>'',
		),
		149 => array (
			'name'=>'#guineabissau',
			'count'=>0,
			'besttraveltime'=>'12',
			'group'=>'',
		),
		150 => array (
			'name'=>'#guyana',
			'count'=>0,
			'besttraveltime'=>'124',
			'group'=>'',
		),
		151 => array (
			'name'=>'#hainan',
			'count'=>0,
			'besttraveltime'=>'124',
			'group'=>'#china',
		),
		152 => array (
			'name'=>'#haiti',
			'count'=>0,
			'besttraveltime'=>'13',
			'group'=>'',
		),
		153 => array (
			'name'=>'#hivaoa',
			'count'=>0,
			'besttraveltime'=>'234',
			'group'=>'#frenchpolynesia',
		),
		154 => array (
			'name'=>'#holland',
			'count'=>0,
			'besttraveltime'=>'234',
			'group'=>'#netherlands',
		),
		155 => array (
			'name'=>'#honduras',
			'count'=>0,
			'besttraveltime'=>'12',
			'group'=>'',
		),
		156 => array (
			'name'=>'#hongkong',
			'count'=>0,
			'besttraveltime'=>'24',
			'group'=>'',
		),
		157 => array (
			'name'=>'#huahine',
			'count'=>0,
			'besttraveltime'=>'234',
			'group'=>'#frenchpolynesia',
		),
		158 => array (
			'name'=>'#hungary',
			'count'=>0,
			'besttraveltime'=>'4',
			'group'=>'',
		),
		159 => array (
			'name'=>'#iceland',
			'count'=>0,
			'besttraveltime'=>'134',
			'group'=>'',
		),
		160 => array (
			'name'=>'#india ',
			'count'=>0,
			'besttraveltime'=>'134',
			'group'=>'',
		),
		161 => array (
			'name'=>'#indonesia',
			'count'=>0,
			'besttraveltime'=>'234',
			'group'=>'',
		),
		162 => array (
			'name'=>'#iran',
			'count'=>0,
			'besttraveltime'=>'24',
			'group'=>'',
		),
		163 => array (
			'name'=>'#iraq',
			'count'=>0,
			'besttraveltime'=>'24',
			'group'=>'',
		),
		164 => array (
			'name'=>'#ireland',
			'count'=>0,
			'besttraveltime'=>'3',
			'group'=>'',
		),
		165 => array (
			'name'=>'#irianbarat',
			'count'=>0,
			'besttraveltime'=>'4',
			'group'=>'#indonesia',
		),
		166 => array (
			'name'=>'#isleofpines',
			'count'=>0,
			'besttraveltime'=>'1234',
			'group'=>'#cuba',
		),
		167 => array (
			'name'=>'#israel',
			'count'=>0,
			'besttraveltime'=>'24',
			'group'=>'',
		),
		168 => array (
			'name'=>'#issas',
			'count'=>0,
			'besttraveltime'=>'1',
			'group'=>'#djibouti',
		),
		169 => array (
			'name'=>'#italy',
			'count'=>0,
			'besttraveltime'=>'234',
			'group'=>'',
		),
		170 => array (
			'name'=>'#ivorycoast',
			'count'=>0,
			'besttraveltime'=>'124',
			'group'=>'',
		),
		171 => array (
			'name'=>'#jamaica',
			'count'=>0,
			'besttraveltime'=>'12',
			'group'=>'',
		),
		172 => array (
			'name'=>'#japan',
			'count'=>0,
			'besttraveltime'=>'23',
			'group'=>'',
		),
		173 => array (
			'name'=>'#johore',
			'count'=>0,
			'besttraveltime'=>'1',
			'group'=>'#malaysia',
		),
		174 => array (
			'name'=>'#jerseychannelislands',
			'count'=>0,
			'besttraveltime'=>'234',
			'group'=>'#greatbritain',
		),
		175 => array (
			'name'=>'#jordan',
			'count'=>0,
			'besttraveltime'=>'24',
			'group'=>'',
		),
		176 => array (
			'name'=>'#kalymnos',
			'count'=>0,
			'besttraveltime'=>'1234',
			'group'=>'#greece',
		),
		177 => array (
			'name'=>'#cambodia',
			'count'=>0,
			'besttraveltime'=>'14',
			'group'=>'',
		),
		178 => array (
			'name'=>'#karpathos',
			'count'=>0,
			'besttraveltime'=>'34',
			'group'=>'#greece',
		),
		179 => array (
			'name'=>'#kassos',
			'count'=>0,
			'besttraveltime'=>'3',
			'group'=>'#greece',
		),
		180 => array (
			'name'=>'#kastellorizon',
			'count'=>0,
			'besttraveltime'=>'34',
			'group'=>'#greece',
		),
		181 => array (
			'name'=>'#kazakhstan',
			'count'=>0,
			'besttraveltime'=>'3',
			'group'=>'',
		),
		182 => array (
			'name'=>'#kedah',
			'count'=>0,
			'besttraveltime'=>'123',
			'group'=>'#malaysia',
		),
		183 => array (
			'name'=>'#kelantan',
			'count'=>0,
			'besttraveltime'=>'1234',
			'group'=>'#malaysia',
		),
		184 => array (
			'name'=>'#kenya',
			'count'=>0,
			'besttraveltime'=>'134',
			'group'=>'',
		),
		185 => array (
			'name'=>'#kiribati',
			'count'=>0,
			'besttraveltime'=>'4',
			'group'=>'',
		),
		186 => array (
			'name'=>'#northkorea',
			'count'=>0,
			'besttraveltime'=>'4',
			'group'=>'',
		),
		187 => array (
			'name'=>'#korea',
			'count'=>0,
			'besttraveltime'=>'34',
			'group'=>'',
		),
		188 => array (
			'name'=>'#kos',
			'count'=>0,
			'besttraveltime'=>'34',
			'group'=>'#greece',
		),
		189 => array (
			'name'=>'#kosovo',
			'count'=>0,
			'besttraveltime'=>'23',
			'group'=>'',
		),
		190 => array (
			'name'=>'#kowloon',
			'count'=>0,
			'besttraveltime'=>'14',
			'group'=>'#hongkong',
		),
		191 => array (
			'name'=>'#kuwait',
			'count'=>0,
			'besttraveltime'=>'1',
			'group'=>'',
		),
		192 => array (
			'name'=>'#kyrgyzstan',
			'count'=>0,
			'besttraveltime'=>'234',
			'group'=>'',
		),
		193 => array (
			'name'=>'#labuan',
			'count'=>0,
			'besttraveltime'=>'234',
			'group'=>'#malaysia',
		),
		194 => array (
			'name'=>'#laos',
			'count'=>0,
			'besttraveltime'=>'2',
			'group'=>'',
		),
		195 => array (
			'name'=>'#latvia',
			'count'=>0,
			'besttraveltime'=>'3',
			'group'=>'',
		),
		196 => array (
			'name'=>'#lebanon',
			'count'=>0,
			'besttraveltime'=>'2',
			'group'=>'',
		),
		197 => array (
			'name'=>'#leipsos',
			'count'=>0,
			'besttraveltime'=>'234',
			'group'=>'#greece',
		),
		198 => array (
			'name'=>'#leros',
			'count'=>0,
			'besttraveltime'=>'34',
			'group'=>'#greece',
		),
		199 => array (
			'name'=>'#liberia',
			'count'=>0,
			'besttraveltime'=>'12',
			'group'=>'',
		),
		200 => array (
			'name'=>'#libya',
			'count'=>0,
			'besttraveltime'=>'12',
			'group'=>'',
		), ////////////////////////////////////////////////////////////////////
		201 => array (
			'name'=>'#liechtenstein', 
			'count'=>0,
			'besttraveltime'=>'3',
			'group'=>'',
		),
		202 => array (
			'name'=>'#lithuania',
			'count'=>0,
			'besttraveltime'=> '3',
			'group'=>'',
		),
		203 => array (
			'name'=>'#lordhowisland', 
			'count'=>0,
			'besttraveltime'=> '124',
			'group'=>'#newcaledonia',
		),
		204 => array (
			'name'=>'#luxembourg', 
			'count'=>0,
			'besttraveltime'=> '3',
			'group'=>'',
		),
		205 => array (
			'name'=>'#macao', 
			'count'=>0,
			'besttraveltime'=> '4',
			'group'=>'',
		),
		206 => array (
			'name'=>'#macau',
			'count'=>0,
			'besttraveltime'=> '4',
			'group'=>'#macao',
		),
		207 => array (
			'name'=>'#alberta', 
			'count'=>0,
			'besttraveltime'=> '3',
			'group'=>'#canada',
		),
		208 => array (
			'name'=>'#macedonia', 
			'count'=>0,
			'besttraveltime'=> '3',
			'group'=>'', 
		),
		209 => array (
			'name'=>'#madagascar',
			'count'=>0,
			'besttraveltime'=> '24',
			'group'=>'',
		),
		210 => array (
			'name'=>'#madeira', 
			'count'=>0,
			'besttraveltime'=> '1234',
			'group'=>'',
		),
		211 => array (
			'name'=>'#majuro', 
			'count'=>0,
			'besttraveltime'=> '1234',
			'group'=>'#marshallislands',
		),
		212 => array (
			'name'=>'#malacca',
			'count'=>0,
			'besttraveltime'=> '1234',
			'group'=>'#malaysia',
		),
		213 => array (
			'name'=>'#malawi',
			'count'=>0,
			'besttraveltime'=> '3',
			'group'=>'',
		),
		214 => array (
			'name'=>'#maldives',
			'count'=>0,
			'besttraveltime'=> '12',
			'group'=>'',
		),
		215 => array (
			'name'=>'#mali',
			'count'=>0,
			'besttraveltime'=> '1',
			'group'=>'',
		),
		216 => array (
			'name'=>'#malta',
			'count'=>0,
			'besttraveltime'=> '34',
			'group'=>'',
		),
		217 => array (
			'name'=>'#manahiki', 
			'count'=>0,
			'besttraveltime'=> '34',
			'group'=>'#newzealand',
		),
		218 => array (
			'name'=>'#manchuria', 
			'count'=>0,
			'besttraveltime'=> '234',
			'group'=>'#china',
		),
		219 => array (
			'name'=>'#manitoba',
			'count'=>0,
			'besttraveltime'=> '3',
			'group'=>'#canada',
		),
		220 => array (
			'name'=>'#mariegalante',
			'count'=>0,
			'besttraveltime'=> '12',
			'group'=>'#caribbeanislands',
		),
		221 => array (
			'name'=>'#marquesas',
			'count'=>0,
			'besttraveltime'=> '234',
			'group'=>'#frenchpolynesia',
		),
		222 => array (
			'name'=>'#marshallislands',
			'count'=>0,
			'besttraveltime'=> '12',
			'group'=>'',
		),
		223 => array (
			'name'=>'#martinique',
			'count'=>0,
			'besttraveltime'=> '12',
			'group'=>'#caribbeanislands',
		),
		224 => array (
			'name'=>'#mauritius',
			'count'=>0,
			'besttraveltime'=> '24',
			'group'=>'',
		),
		225 => array (
			'name'=>'#mayotte', 
			'count'=>0,
			'besttraveltime'=> '34',
			'group'=>'#comoros',
		),
		226 => array (
			'name'=>'#saintpierreetmiquelon',
			'count'=>0,
			'besttraveltime'=> '3',
			'group'=>'#saintpierre',
		),
		227 => array (
			'name'=>'#moheli',
			'count'=>0,
			'besttraveltime'=> '34',
			'group'=>'#comoros',
		),
		228 => array (
			'name'=>'#moldova',
			'count'=>0,
			'besttraveltime'=>'234',
			'group'=>'',
		),
		229 => array (
			'name'=>'#monaco',
			'count'=>0,
			'besttraveltime'=> '34',
			'group'=>'',
		),
		230 => array (
			'name'=>'#mongolia',
			'count'=>0,
			'besttraveltime'=> '3',
			'group'=>'',
		),
		231 => array (
			'name'=>'#montenegro',
			'count'=>0,
			'besttraveltime'=> '3',
			'group'=>'',
		),
		232 => array (
			'name'=>'#montserrat',
			'count'=>0,
			'besttraveltime'=> '12',
			'group'=>'#caribbeanislands',
		),
		233 => array (
			'name'=>'#moorea',
			'count'=>0,
			'besttraveltime'=> '234',
			'group'=>'#frenchpolynesia',
		),
		234 => array (
			'name'=>'#morocco',
			'count'=>0,
			'besttraveltime'=>'24',
			'group'=>'',
		),
		235 => array (
			'name'=>'#mozambique',
			'count'=>0,
			'besttraveltime'=> '234',
			'group'=>'',
		),
		236 => array (
			'name'=>'#muscat ',
			'count'=>0,
			'besttraveltime'=> '14',
			'group'=>'#oman ',
		),
		237 => array (
			'name'=>'#myanmar',
			'count'=>0,
			'besttraveltime'=> '14',
			'group'=>'#burma',
		),
		238 => array (
			'name'=>'#namibia',
			'count'=>0,
			'besttraveltime'=> '3',
			'group'=>'',
		),
		239 => array (
			'name'=>'#nauru',
			'count'=>0,
			'besttraveltime'=> '1234',
			'group'=>'',
		),
		240 => array (
			'name'=>'#negrisembilan',
			'count'=>0,
			'besttraveltime'=> '234',
			'group'=>'#malaysia',
		),
		241 => array (
			'name'=>'#sintmarteen',
			'count'=>0,
			'besttraveltime'=>'12',
			'group'=>'#caribbeanislands',
		),
		242 => array (
			'name'=>'#nepal',
			'count'=>0,
			'besttraveltime'=>'24',
			'group'=>'',
		),
		243 => array (
			'name'=>'#newbritain',
			'count'=>0,
			'besttraveltime'=>'34',
			'group'=>'#papuanewguinea',
		),
		244 => array (
			'name'=>'#newbrunswick',
			'count'=>0,
			'besttraveltime'=>'3',
			'group'=>'#canada',
		),
		245 => array (
			'name'=>'#newcaledonia',
			'count'=>0,
			'besttraveltime'=>'4',
			'group'=>'',
		),
		246 => array (
			'name'=>'#newhanover',
			'count'=>0,
			'besttraveltime'=>'34',
			'group'=>'#papuanewguinea',
		),
		247 => array (
			'name'=>'#newireland',
			'count'=>0,
			'besttraveltime'=>'234',
			'group'=>'#papuanewguinea',
		),
		248 => array (
			'name'=>'#newsouthwales',
			'count'=>0,
			'besttraveltime'=>'12',
			'group'=>'#australia',
		),
		249 => array (
			'name'=>'#newzealand',
			'count'=>0,
			'besttraveltime'=>'1234',
			'group'=>'',
		),
		250 => array (
			'name'=>'#newfoundland',
			'count'=>0,
			'besttraveltime'=>'3',
			'group'=>'#canada',
		),
		251 => array (
			'name'=>'#nicaragua',
			'count'=>0,
			'besttraveltime'=>'12',
			'group'=>'',
		),
		252 => array (
			'name'=>'#niger',
			'count'=>0,
			'besttraveltime'=>'1',
			'group'=>'',
		),
		253 => array (
			'name'=>'#nigeria',
			'count'=>0,
			'besttraveltime'=>'14',
			'group'=>'#papanewguinea',
		),
		254 => array (
			'name'=>'#nisyros',
			'count'=>0,
			'besttraveltime'=>'3',
			'group'=>'#greece',
		),
		255 => array (
			'name'=>'#niue',
			'count'=>0,
			'besttraveltime'=>'34',
			'group'=>'#newzealand',
		),
		256 => array (
			'name'=>'#norfolkisland',
			'count'=>0,
			'besttraveltime'=>'14',
			'group'=>'#australia',
		),
		257 => array (
			'name'=>'#northborneo',
			'count'=>0,
			'besttraveltime'=>'23',
			'group'=>'#malaysia',
		),
		258 => array (
			'name'=>'#zimbabwe',
			'count'=>0,
			'besttraveltime'=>'14',
			'group'=>'',
		),
		259 => array (
			'name'=>'#northireland',
			'count'=>0,
			'besttraveltime'=>'3',
			'group'=>'#greatbritain',
		),
		260 => array (
			'name'=>'#nukahiva',
			'count'=>0,
			'besttraveltime'=>'234',
			'group'=>'#frenchpolynesia',
		),
		261 => array (
			'name'=>'#zambia',
			'count'=>0,
			'besttraveltime'=>'3',
			'group'=>'',
		),
		262 => array (
			'name'=>'#okinawa',
			'count'=>0,
			'besttraveltime'=>'24',
			'group'=>'#japan',
		),
		263 => array (
			'name'=>'#oman ',
			'count'=>0,
			'besttraveltime'=>'12',
			'group'=>'',
		),
		264 => array (
			'name'=>'#ontario',
			'count'=>0,
			'besttraveltime'=>'34',
			'group'=>'#canada',
		),
		265 => array (
			'name'=>'#srilanka',
			'count'=>0,
			'besttraveltime'=>'1234',
			'group'=>'',
		),
		266 => array (
			'name'=>'#sudan',
			'count'=>0,
			'besttraveltime'=>'124',
			'group'=>'',
		),
		267 => array (
			'name'=>'#pahang',
			'count'=>0,
			'besttraveltime'=>'2',
			'group'=>'#malaysia',
		),
		268 => array (
			'name'=>'#pakistan',
			'count'=>0,
			'besttraveltime'=>'14',
			'group'=>'',
		),
		269 => array (
			'name'=>'#panama',
			'count'=>0,
			'besttraveltime'=>'12',
			'group'=>'#kiribati',
		),
		270 => array (
			'name'=>'#papuanewguinea',
			'count'=>0,
			'besttraveltime'=>'3',
			'group'=>'',
		),
		271 => array (
			'name'=>'#paraguay',
			'count'=>0,
			'besttraveltime'=>'4',
			'group'=>'',
		),
		272 => array (
			'name'=>'#patmos',
			'count'=>0,
			'besttraveltime'=>'34',
			'group'=>'#greece',
		),
		273 => array (
			'name'=>'#pemba',
			'count'=>0,
			'besttraveltime'=>'134',
			'group'=>'#tanzania',
		),
		274 => array (
			'name'=>'#penang',
			'count'=>0,
			'besttraveltime'=>'1',
			'group'=>'#malaysia',
		),
		275 => array (
			'name'=>'#perak',
			'count'=>0,
			'besttraveltime'=>'2',
			'group'=>'#malaysia',
		),
		276 => array (
			'name'=>'#perlois',
			'count'=>0,
			'besttraveltime'=>'123',
			'group'=>'#malaysia',
		),
		277 => array (
			'name'=>'#persia',
			'count'=>0,
			'besttraveltime'=>'24',
			'group'=>'#iran',
		),
		278 => array (
			'name'=>'#peru',
			'count'=>0,
			'besttraveltime'=>'3',
			'group'=>'',
		),
		279 => array (
			'name'=>'#pescadores',
			'count'=>0,
			'besttraveltime'=>'1234',
			'group'=>'#taiwan',
		),
		280 => array (
			'name'=>'#petiteterre',
			'count'=>0,
			'besttraveltime'=>'12',
			'group'=>'#caribbeanislands',
		),
		281 => array (
			'name'=>'#philippines',
			'count'=>0,
			'besttraveltime'=>'12',
			'group'=>'#australia',
		),
		282 => array (
			'name'=>'#poland',
			'count'=>0,
			'besttraveltime'=>'3',
			'group'=>'',
		),
		283 => array (
			'name'=>'#portugal',
			'count'=>0,
			'besttraveltime'=>'234',
			'group'=>'',
		),
		284 => array (
			'name'=>'#puertorico',
			'count'=>0,
			'besttraveltime'=>'12',
			'group'=>'',
		),
		285 => array (
			'name'=>'#qatar',
			'count'=>0,
			'besttraveltime'=>'2',
			'group'=>'',
		),
		286 => array (
			'name'=>'#quebec',
			'count'=>0,
			'besttraveltime'=>'34',
			'group'=>'#canada',
		),
		287 => array (
			'name'=>'#queensland',
			'count'=>0,
			'besttraveltime'=>'234',
			'group'=>'#australia',
		),
		288 => array (
			'name'=>'#quemoy',
			'count'=>0,
			'besttraveltime'=>'234',
			'group'=>'#taiwan',
		),
		289 => array (
			'name'=>'#raiatea',
			'count'=>0,
			'besttraveltime'=>'234',
			'group'=>'#frenchpolynesia',
		),
		290 => array (
			'name'=>'#rakaanga',
			'count'=>0,
			'besttraveltime'=>'',
			'group'=>'#newzealand',
		),
		291 => array (
			'name'=>'#rapa',
			'count'=>0,
			'besttraveltime'=>'234',
			'group'=>'#frenchpolynesia',
		),
		292 => array (
			'name'=>'#rasalkaimah',
			'count'=>0,
			'besttraveltime'=>'124',
			'group'=>'#emirates',
		),
		293 => array (
			'name'=>'#redonda',
			'count'=>0,
			'besttraveltime'=>'123',
			'group'=>'#caribbeanislands',
		),
		294 => array (
			'name'=>'#reunion',
			'count'=>0,
			'besttraveltime'=>'34',
			'group'=>'#mauritius',
		),
		295 => array (
			'name'=>'#romania',
			'count'=>0,
			'besttraveltime'=>'3',
			'group'=>'',
		),
		296 => array (
			'name'=>'#russia',
			'count'=>0,
			'besttraveltime'=>'3',
			'group'=>'',
		),
		297 => array (
			'name'=>'#suriname',
			'count'=>0,
			'besttraveltime'=>'234',
			'group'=>'',
		),
		298 => array (
			'name'=>'#swaziland',
			'count'=>0,
			'besttraveltime'=>'1234',
			'group'=>'',
		),
		299 => array (
			'name'=>'#rwanda',
			'count'=>0,
			'besttraveltime'=>'3',
			'group'=>'',
		),
		300 => array (
			'name'=>'#sabah',
			'count'=>0,
			'besttraveltime'=>'12',
			'group'=>'#malaysia',
		),
		301 => array (
			'name'=>'#saintbarthelemy',
			'count'=>0,
			'besttraveltime'=>'23',
			'group'=>'#guadeloupe',
		),
		302 =>array (
			'name'=>'#saintpierre',
			'count'=>0,
			'besttraveltime'=>'3',
			'group'=>'',
		),
		303 => array (
			'name'=>'#sainthelena',
			'count'=>0,
			'besttraveltime'=>'1',
			'group'=>'#caribbeanislands',
		),
		304 => array (
			'name'=>'#saintlucia',
			'count'=>0,
			'besttraveltime'=>'12',
			'group'=>'#caribbeanislands',
		),
		305 => array (
			'name'=>'#saintmartin',
			'count'=>0,
			'besttraveltime'=>'12',
			'group'=>'#caribbeanislands',
		),
		306 => array (
			'name'=>'#saintmarie',
			'count'=>0,
			'besttraveltime'=>'34',
			'group'=>'#madagascar',
		),
		307 => array (
			'name'=>'#salvador',
			'count'=>0,
			'besttraveltime'=>'12',
			'group'=>'#elsalvador',
		),
		308 => array (
			'name'=>'#samoa',
			'count'=>0,
			'besttraveltime'=>'34',
			'group'=>'',
		),
		309 => array (
			'name'=>'#sanmarino',
			'count'=>0,
			'besttraveltime'=>'3',
			'group'=>'',
		),
		310 => array (
			'name'=>'#elsalvador',
			'count'=>0,
			'besttraveltime'=>'12',
			'group'=>'',
		),
		311 => array (
			'name'=>'#santacruzislands',
			'count'=>0,
			'besttraveltime'=>'12',
			'group'=>'#greatbritain',
		),
		312 => array (
			'name'=>'#saotome',
			'count'=>0,
			'besttraveltime'=>'3',
			'group'=>'',
		),
		313 => array (
			'name'=>'#sarawak',
			'count'=>0,
			'besttraveltime'=>'234',
			'group'=>'#malaysia',
		),
		314 => array (
			'name'=>'#sark',
			'count'=>0,
			'besttraveltime'=>'34',
			'group'=>'#greatbritain',
		),
		315 => array (
			'name'=>'#saudiarabia',
			'count'=>0,
			'besttraveltime'=>'1',
			'group'=>'',
		),
		316 => array (
			'name'=>'#savageisland',
			'count'=>0,
			'besttraveltime'=>'',
			'group'=>'#newzealand',
		),
		317 => array (
			'name'=>'#savaii',
			'count'=>0,
			'besttraveltime'=>'',
			'group'=>'#samoa',
		),
		318 => array (
			'name'=>'#scotland',
			'count'=>0,
			'besttraveltime'=>'',
			'group'=>'',
		),
		319 => array (
			'name'=>'#senegal',
			'count'=>0,
			'besttraveltime'=>'',
			'group'=>'',
		),
		320 => array (
			'name'=>'#serbia',
			'count'=>0,
			'besttraveltime'=>'',
			'group'=>'',
		),
		321 => array (
			'name'=>'#seychelles',
			'count'=>0,
			'besttraveltime'=>'',
			'group'=>'#mauritius',
		),
		322 => array (
			'name'=>'#sharja',
			'count'=>0,
			'besttraveltime'=>'',
			'group'=>'#emirates',
		),
		323 => array (
			'name'=>'#sierraleone',
			'count'=>0,
			'besttraveltime'=>'',
			'group'=>'',
		),
		324 => array (
			'name'=>'#shikoku',
			'count'=>0,
			'besttraveltime'=>'',
			'group'=>'#japan',
		),
		325 => array (
			'name'=>'#sikkim',
			'count'=>0,
			'besttraveltime'=>'',
			'group'=>'#india ',
		),
		326 => array (
			'name'=>'#singapore',
			'count'=>0,
			'besttraveltime'=>'',
			'group'=>'',
		),
		327 => array (
			'name'=>'#sinteutatius',
			'count'=>0,
			'besttraveltime'=>'',
			'group'=>'#curacao',
		),
		328 => array (
			'name'=>'#sintmaarten',
			'count'=>0,
			'besttraveltime'=>'',
			'group'=>'#caribbeanislands',
		),
		329 => array (
			'name'=>'#slovakia',
			'count'=>0,
			'besttraveltime'=>'',
			'group'=>'',
		),
		330 => array (
			'name'=>'#slovenia',
			'count'=>0,
			'besttraveltime'=>'',
			'group'=>'',
		),
		331 => array (
			'name'=>'#somalia',
			'count'=>0,
			'besttraveltime'=>'',
			'group'=>'',
		),
		332 => array (
			'name'=>'#southafrica',
			'count'=>0,
			'besttraveltime'=>'',
			'group'=>'',
		),
		333 => array (
			'name'=>'#southaustralia',
			'count'=>0,
			'besttraveltime'=>'',
			'group'=>'#australia',
		),
		334 => array (
			'name'=>'#southkorea',
			'count'=>0,
			'besttraveltime'=>'',
			'group'=>'#korea',
		),
		335 => array (
			'name'=>'#spain',
			'count'=>0,
			'besttraveltime'=>'',
			'group'=>'',
		),
		336 => array (
			'name'=>'#spitzbergen',
			'count'=>0,
			'besttraveltime'=>'',
			'group'=>'#norway',
		),
		337 => array (
			'name'=>'#switzerland',
			'count'=>0,
			'besttraveltime'=>'',
			'group'=>'',
		),
		338 => array (
			'name'=>'#syria',
			'count'=>0,
			'besttraveltime'=>'',
			'group'=>'',
		),
		339 => array (
			'name'=>'#tahaa',
			'count'=>0,
			'besttraveltime'=>'',
			'group'=>'#frenchpolynesia',
		),
		340 => array (
			'name'=>'#tahiti',
			'count'=>0,
			'besttraveltime'=>'234',
			'group'=>'#frenchpolynesia',
		),
		341 => array (
			'name'=>'#taiwan',
			'count'=>0,
			'besttraveltime'=>'',
			'group'=>'',
		),
		342 => array (
			'name'=>'#tajikistan',
			'count'=>0,
			'besttraveltime'=>'',
			'group'=>'',
		),
		343 => array (
			'name'=>'#tanzania',
			'count'=>0,
			'besttraveltime'=>'',
			'group'=>'',
		),
		344 => array (
			'name'=>'#tschad',
			'count'=>0,
			'besttraveltime'=>'',
			'group'=>'#chad',
		),
		345 => array (
			'name'=>'#thailand',
			'count'=>0,
			'besttraveltime'=>'',
			'group'=>'',
		),
		346 => array (
			'name'=>'#thursdayisland',
			'count'=>0,
			'besttraveltime'=>'',
			'group'=>'#australia',
		),
		347 => array (
			'name'=>'#tibet',
			'count'=>0,
			'besttraveltime'=>'',
			'group'=>'#china',
		),
		348 => array (
			'name'=>'#thilos',
			'count'=>0,
			'besttraveltime'=>'',
			'group'=>'#greece',
		),
		349 => array (
			'name'=>'#timor',
			'count'=>0,
			'besttraveltime'=>'',
			'group'=>'#indonesia',
		),
		350 => array (
			'name'=>'#togo',
			'count'=>0,
			'besttraveltime'=>'',
			'group'=>'',
		),
		351 => array (
			'name'=>'#tokelau',
			'count'=>0,
			'besttraveltime'=>'',
			'group'=>'#samoa',
		),
		352 => array (
			'name'=>'#tonga',
			'count'=>0,
			'besttraveltime'=>'',
			'group'=>'',
		),
		353 => array (
			'name'=>'#torishima',
			'count'=>0,
			'besttraveltime'=>'',
			'group'=>'#japan',
		),
		354 => array (
			'name'=>'#tobago',
			'count'=>0,
			'besttraveltime'=>'',
			'group'=>'',
		),
		355 => array (
			'name'=>'#trinidad',
			'count'=>0,
			'besttraveltime'=>'',
			'group'=>'#tobago',
		),
		356 => array (
			'name'=>'#tripolitania',
			'count'=>0,
			'besttraveltime'=>'',
			'group'=>'#libya',
		),
		357 => array (
			'name'=>'#trucialstates',
			'count'=>0,
			'besttraveltime'=>'',
			'group'=>'#emirates',
		),
		358 => array (
			'name'=>'#tuamotou',
			'count'=>0,
			'besttraveltime'=>'234',
			'group'=>'#frenchpolynesia',
		),
		359 => array (
			'name'=>'#tubuai',
			'count'=>0,
			'besttraveltime'=>'234',
			'group'=>'#frenchpolynesia',
		),
		360 => array (
			'name'=>'#tunisia',
			'count'=>0,
			'besttraveltime'=>'',
			'group'=>'',
		),
		361 => array (
			'name'=>'#turkey',
			'count'=>0,
			'besttraveltime'=>'',
			'group'=>'',
		),
		362 => array (
			'name'=>'#turkmenistan',
			'count'=>0,
			'besttraveltime'=>'',
			'group'=>'',
		),
		363 => array (
			'name'=>'#turksandcaicosislands',
			'count'=>0,
			'besttraveltime'=>'',
			'group'=>'',
		),
		364 => array (
			'name'=>'#tuvalu',
			'count'=>0,
			'besttraveltime'=>'',
			'group'=>'',
		),
		365 => array (
			'name'=>'#uganda',
			'count'=>0,
			'besttraveltime'=>'',
			'group'=>'',
		),
		366 => array (
			'name'=>'#ukraine',
			'count'=>0,
			'besttraveltime'=>'',
			'group'=>'',
		),
		367 => array (
			'name'=>'#greatbritain',
			'count'=>0,
			'besttraveltime'=>'3',
			'group'=>'',
		),
		368 => array (
			'name'=>'#uruguay',
			'count'=>0,
			'besttraveltime'=>'1',
			'group'=>'#djibouti',
		),
		369 => array (
			'name'=>'#uzbekistan',
			'count'=>0,
			'besttraveltime'=>'4',
			'group'=>'',
		),
		370 => array (
			'name'=>'#vanuatu',
			'count'=>0,
			'besttraveltime'=>'3',
			'group'=>'',
		),
		371 => array (
			'name'=>'#vatican',
			'count'=>0,
			'besttraveltime'=>'24',
			'group'=>'',
		),
		372 => array (
			'name'=>'#venezuela',
			'count'=>0,
			'besttraveltime'=>'1',
			'group'=>'',
		),
		373 => array (
			'name'=>'#vietnam',
			'count'=>0,
			'besttraveltime'=>'3',
			'group'=>'',
		),
		374 => array (
			'name'=>'#wales',
			'count'=>0,
			'besttraveltime'=>'3',
			'group'=>'',
		),
		375 => array (
			'name'=>'#yemen',
			'count'=>0,
			'besttraveltime'=>'24',
			'group'=>'',
		),
		376 => array (
			'name'=>'Testcounter',
			'count'=>0,
			'besttraveltime'=>'',
			'group'=>'',
		),
		


	);


	$json_countryarray = json_encode($countryarray);
	$test_country = 'countryarraytest' . '.json';

	if (file_put_contents($test_country,$json_countryarray)){
		echo $test_country . 'file created';
	}else{
		echo 'error';
	};

?>